language: python

python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - build-essential
    - libudunits2-dev
    - libnetcdf-dev
    - netcdf-bin
    - python3-dev

env:
  global:
    - CHECKER_VERSION=4.1.1

install:
  - pip install compliance-checker==$CHECKER_VERSION
  - pip install -e .
  - pip install pytest

script:
- pytest
